Create method to get a generic json
ThiagoAquino/knot-mqtt pull request #1
Opened 2023-08-16 13:15 UTC by ThiagoAquino

2023-08-16 23:49 UTC, janael-pinheiro requested changes, later dismissed

2023-08-16 23:49 UTC, janael-pinheiro commented on cmd/main.go
> -	// Configura o QoS para 2 (entrega exatamente uma vez)
Esse comentário pode ser removido, pois o código expressa claramente a sua intenção.

2023-08-16 23:49 UTC, janael-pinheiro commented on cmd/main.go
>  	client := application.ConfigureClient(mqttConfiguration)
Esse comentário pode ser removido, pois o código expressa claramente a sua intenção.

2023-08-16 23:49 UTC, janael-pinheiro commented on cmd/main.go
> +	fmt.Println(mqttDeviceConfiguration)
```suggestion
```

2023-08-16 23:49 UTC, janael-pinheiro commented on cmd/main.go
>  	fmt.Println()
```suggestion
```

2023-08-16 23:49 UTC, janael-pinheiro commented on internal/entities/measurement.go
>  type Statement struct {
Essa estrutura é utilizada?

2023-08-16 23:49 UTC, janael-pinheiro commented on internal/utils/configuration_parser.go
> +	"io/ioutil"
```suggestion
	"os"
```

2023-08-16 23:49 UTC, janael-pinheiro commented on internal/utils/configuration_parser.go
>  	fileContent, err := ioutil.ReadFile(filepath.Clean(filepathName))
```suggestion
	fileContent, err := os.ReadFile(filepath.Clean(filepathName))
```

2023-08-16 23:49 UTC, janael-pinheiro commented on pkg/application/mqtt_consumer.go
>  		fmt.Println(token.Error())
```suggestion
		log.Println(token.Error())
```

2023-08-16 23:49 UTC, janael-pinheiro commented on pkg/application/mqtt_consumer.go
> +
Remover código comentado.

2023-08-16 23:49 UTC, janael-pinheiro commented on pkg/application/mqtt_consumer.go
> +	fmt.Println(data)
```suggestion
```

2023-08-16 23:49 UTC, janael-pinheiro commented on pkg/application/mqtt_consumer.go
> +		value, _ := data[config.Value]
Verificar se `value`, `name`, `times` e `sensorType` estão presentes no `map`.
```suggestion
		value, ok := data[config.Value]
		if !ok {
			continue
		}
```

2023-08-16 23:49 UTC, janael-pinheiro commented on pkg/application/mqtt_consumer.go
> +		times, _ := data[config.Timestamp]
```suggestion
		timestamp, _ := data[config.Timestamp]
```

2023-08-16 23:49 UTC, janael-pinheiro commented on pkg/application/mqtt_consumer.go
> +		fmt.Println("Value:", value)
```suggestion
```

2023-08-16 23:49 UTC, janael-pinheiro commented on pkg/application/mqtt_consumer.go
> +		fmt.Println("Name:", name)
```suggestion
```

2023-08-16 23:49 UTC, janael-pinheiro commented on pkg/application/mqtt_consumer.go
> +		fmt.Println("times:", times)
```suggestion
```

2023-08-16 23:49 UTC, janael-pinheiro commented on pkg/application/mqtt_consumer.go
> +		fmt.Println("sensorType:", sensorType)
```suggestion
```

2023-08-16 23:49 UTC, janael-pinheiro commented on pkg/application/mqtt_consumer.go
> +		for _ = range capturedData.Data {
```suggestion
		for range capturedData.Data {
```

2023-08-16 23:49 UTC, janael-pinheiro commented on pkg/application/mqtt_consumer.go
> +	//// Construir a estrutura final removendo os campos indesejados
Remover o código comentado.

2023-08-17 19:07 UTC, ThiagoAquino commented on internal/entities/measurement.go
>  type Statement struct {
É sim, pois o value poder ser um int, um float, uma string ou um boleano

2023-08-21 11:29 UTC, janael-pinheiro approved these changes

2023-08-23 12:22 UTC, rtorresmatheus submitted a review, later dismissed
Bom trabalho, pessoal!

2023-08-23 12:22 UTC, rtorresmatheus commented on cmd/main.go
> +	for i := 0; i < len(mqttDeviceConfigSensorDetails); i++ {
Essa variável i corresponde a o que?

2023-08-23 12:22 UTC, rtorresmatheus commented on cmd/main.go
>  	knotConfiguration, err := utils.ConfigurationParser("internal/configuration/knot_setup.yaml", entities.IntegrationKNoTConfig{})
Esses locais dos arquivos de configurações, podem ficar em constantes ou variáveis de ambientes, para possibilitar no futuro a mudança do nome, local, etc. Assim, evitando ficar hardcode

2023-08-23 12:22 UTC, rtorresmatheus commented on internal/configuration/mqtt_device_config.yaml
Tenta adicionar o comentário mostrando um exemplo os tipos possíveis de configurações.

2023-08-23 12:22 UTC, rtorresmatheus commented on pkg/application/mqtt_consumer.go
> +		for i, config := range mqttConfigSensor {
Esse i corresponde a o que?

2023-08-23 12:22 UTC, rtorresmatheus commented on pkg/application/mqtt_consumer.go
> +
.

2023-08-23 12:22 UTC, rtorresmatheus commented on cmd/main.go
Todos os logs em português devem ser passado  para inglês, nada no código pode está em português. Esse código vai ficar opensource

2023-08-23 20:00 UTC, rtorresmatheus approved these changes

2023-08-24 10:37 UTC, merged